const header = document.querySelector('h1');
const pageTitle = document.querySelector('title');
const navBar = document.querySelector('nav');
const footer = document.querySelector('footer');
const leftPane = document.querySelector('#left-pane');
const resHeader = document.querySelector('#left-pane > h2');
const tabBar = document.querySelector('#tab-bar')
const midPane = document.querySelector('#tab-pane');
const rightPane = document.querySelector('#right-pane');
const logHeader = document.querySelector('#right-pane > h2');
const logPane = document.querySelector('#right-pane');
const about = document.querySelector('#about');
const credits = document.querySelector('#credits');
const vNumber = document.querySelector('#version');
let idleDisp = document.createElement('div');
const discoveryFraction = 0.1;
const costMultiplier = 1.15;